### ISSUE TITLE
latest meteor

### ISSUE THREAD

**Issue by interfaith** [new3Rs/meteor-twitter#1]
how to rebuild for the latest meteor ?

**Comment by new3Rs** [comment]
The package (version 0.0.9) in Atmosphere has been working for meteor 1.3.3.1.

This Github repository was old, so I have updated it right now.

If you have any trouble, please let me know it. Thank you.

**Comment by interfaith** [comment]
ReferenceError: Twitter is not defined
1. meteor create testtweet
2. meteor add new3rs:twitter
3. meteor code added 
   Template.hello.events({
   'click button'(event, instance) {
     // increment the counter when button is clicked, keys erased
   var client = new Twitter({
   consumer_key: '',
   consumer_secret: '
   access_token_key: '
   access_token_secret: '
   });
   instance.counter.set(instance.counter.get() + 1);
   },
   });

**Comment by interfaith** [comment]
it was working, thx

**Comment by interfaith** [comment]
1.3.2 is ok  several other issues with 1.3.3.1 for example using external mongodb
so your in with a crowd of issues.

**Comment by y-ich** [comment]
I am sorry that this package is only for server-side.
If you use Twitter on client side, maybe it is by another package.

**Comment by new3Rs** [comment]
I am sorry that this package is only for server-side.
If you use Twitter on client side, maybe it is by another package.

**Comment by interfaith** [comment]
ok ,

## 

---

Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
