### ISSUE TITLE
meteor 1.4 with https

### ISSUE THREAD

**Issue by interfaith** [new3Rs/meteor-twitter#2]
on the server

  console.log("start a tweet");

  var client = new Twitter({
  consumer_key: '',
  consumer_secret: '',
  access_token_key: '',
  access_token_secret: ''
});

Exception while simulating the effect of invoking 'recordfile' ReferenceError: Twitter is not defined(…) ReferenceError: Twitter is not defined

**Comment by interfaith** [comment]
how can this package be re-built for the latest meteor beta 1.4.7 ?

**Comment by new3Rs** [comment]
Thank you for using our package.

We checked it on METEOR@1.4-beta.7 and had no problems.
How about your local environment? and what do you mean 'with https'? Is it a case deploying on https://<example.com>?

**Comment by interfaith** [comment]
yes with https via nourharidy/meteor-ssl as webrtc now demands ssl.
all is ok likely until that package is added. some conflict of packages?

On Thu, Jul 7, 2016 at 4:21 AM, new3Rs notifications@github.com wrote:

> Thank you for using our package.
> 
> We checked it on METEOR@1.4-beta.7 and had no problems.
> How about your local environment? and what do you mean 'with https'? Is it
> a case deploying on https://?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/new3Rs/meteor-twitter/issues/2#issuecomment-231051321,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAs5z2lzS43kBmsokqOR2-xjGHiKG6Xpks5qTOFEgaJpZM4JD884
> .

## 

---

Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by new3Rs** [comment]
We checked it with

```
meteor add nourharidy:ssl
```

and had no problems.

Could you make reproduction code set? Thank you.

**Comment by interfaith** [comment]
will do now

On Thu, Jul 7, 2016 at 5:20 PM, new3Rs notifications@github.com wrote:

> We checked it with
> 
> meteor add nourharidy:ssl
> 
> and had no problems.
> 
> Could you make reproduction code set? Thank you.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/new3Rs/meteor-twitter/issues/2#issuecomment-231244718,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAs5z2Yjv7M2u5cKtn1OkeTqC1Un8rzXks5qTZfIgaJpZM4JD884
> .

## 

---

Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by interfaith** [comment]
fixed
for some reason now this is needed to wrap the methods.
a trap waiting for me to fall into i guess
my apologies

so the server side worked and the client side now somehow gets triggered

if (Meteor.isServer) {
Meteor.methods({

On Thu, Jul 7, 2016 at 5:28 PM, Mark Spowage spowage@gmail.com wrote:

> will do now
> 
> On Thu, Jul 7, 2016 at 5:20 PM, new3Rs notifications@github.com wrote:
> 
> > We checked it with
> > 
> > meteor add nourharidy:ssl
> > 
> > and had no problems.
> > 
> > Could you make reproduction code set? Thank you.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/new3Rs/meteor-twitter/issues/2#issuecomment-231244718,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AAs5z2Yjv7M2u5cKtn1OkeTqC1Un8rzXks5qTZfIgaJpZM4JD884
> > .
> 
> ## 
> 
> ---
> 
> Fight back spam! Download the Blue Frog.
> http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

## 

---

Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D

**Comment by new3Rs** [comment]
Good.
